# Generated by Django 5.1.1 on 2025-04-29 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro_aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='comentario_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='foro_aplicacion.comentario'),
        ),
        migrations.CreateModel(
            name='VotoComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(choices=[(1, 'Like'), (-1, 'Dislike')])),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='foro_aplicacion.comentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_comentarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voto en comentario',
                'verbose_name_plural': 'Votos en comentarios',
                'unique_together': {('comentario', 'usuario')},
            },
        ),
    ]
