# Generated by Django 5.2 on 2025-05-14 23:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro_aplicacion', '0003_usuario_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('like', 'Like a tu publicación'), ('dislike', 'Dislike a tu publicación'), ('comentario', 'Comentario en tu publicación'), ('respuesta', 'Respuesta a tu comentario')], max_length=20)),
                ('mensaje', models.TextField()),
                ('url', models.URLField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
