# Generated by Django 5.2 on 2025-05-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro_aplicacion', '0005_alter_notificacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='publicaciones/'),
        ),
    ]
