# Generated by Django 5.2 on 2025-05-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro_aplicacion', '0006_publicacion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
